"""add_max_duration_seconds_to_survey_element

Revision ID: 4f31cb88cc4a
Revises: fc125248c2cd
Create Date: 2025-06-05 12:27:04.803131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f31cb88cc4a'
down_revision: Union[str, None] = 'fc125248c2cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_elements', sa.Column('max_duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_elements', 'max_duration_seconds')
    # ### end Alembic commands ###
