"""create_initial_tables_from_models

Revision ID: 7968a2aac1a5
Revises: 
Create Date: 2025-05-28 00:57:01.552991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7968a2aac1a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('prolific_enabled', sa.Boolean(), nullable=True),
    sa.Column('prolific_completion_url', sa.String(), nullable=True),
    sa.Column('enable_advanced_tracking', sa.Boolean(), nullable=True),
    sa.Column('track_copy_paste', sa.Boolean(), nullable=True),
    sa.Column('track_tab_focus', sa.Boolean(), nullable=True),
    sa.Column('track_page_duration', sa.Boolean(), nullable=True),
    sa.Column('display_time_spent', sa.Boolean(), nullable=True),
    sa.Column('enable_max_duration', sa.Boolean(), nullable=True),
    sa.Column('max_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('max_duration_warning_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surveys_id'), 'surveys', ['id'], unique=False)
    op.create_index(op.f('ix_surveys_title'), 'surveys', ['title'], unique=False)
    op.create_table('survey_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('element_type', sa.String(), nullable=True),
    sa.Column('question_type', sa.String(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('paste_disabled', sa.Boolean(), nullable=True),
    sa.Column('randomization_group', sa.String(), nullable=True),
    sa.Column('allow_back_navigation', sa.Boolean(), nullable=True),
    sa.Column('llm_assistance_enabled', sa.Boolean(), nullable=True),
    sa.Column('maxlength', sa.Integer(), nullable=True),
    sa.Column('task_identifier', sa.String(), nullable=True),
    sa.Column('references_element_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['references_element_id'], ['survey_elements.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_elements_id'), 'survey_elements', ['id'], unique=False)
    op.create_index(op.f('ix_survey_elements_task_identifier'), 'survey_elements', ['task_identifier'], unique=False)
    op.create_table('survey_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('prolific_pid', sa.String(), nullable=True),
    sa.Column('study_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('page_durations_log', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_participants_id'), 'survey_participants', ['id'], unique=False)
    op.create_index(op.f('ix_survey_participants_prolific_pid'), 'survey_participants', ['prolific_pid'], unique=True)
    op.create_index(op.f('ix_survey_participants_session_id'), 'survey_participants', ['session_id'], unique=False)
    op.create_index(op.f('ix_survey_participants_study_id'), 'survey_participants', ['study_id'], unique=False)
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('survey_element_id', sa.Integer(), nullable=True),
    sa.Column('response_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('llm_chat_history', sa.JSON(), nullable=True),
    sa.Column('paste_count', sa.Integer(), nullable=True),
    sa.Column('focus_lost_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['survey_participants.id'], ),
    sa.ForeignKeyConstraint(['survey_element_id'], ['survey_elements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responses_id'), 'responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_responses_id'), table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_survey_participants_study_id'), table_name='survey_participants')
    op.drop_index(op.f('ix_survey_participants_session_id'), table_name='survey_participants')
    op.drop_index(op.f('ix_survey_participants_prolific_pid'), table_name='survey_participants')
    op.drop_index(op.f('ix_survey_participants_id'), table_name='survey_participants')
    op.drop_table('survey_participants')
    op.drop_index(op.f('ix_survey_elements_task_identifier'), table_name='survey_elements')
    op.drop_index(op.f('ix_survey_elements_id'), table_name='survey_elements')
    op.drop_table('survey_elements')
    op.drop_index(op.f('ix_surveys_title'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_id'), table_name='surveys')
    op.drop_table('surveys')
    # ### end Alembic commands ###
