"""add_displayed_page_ordering_to_response

Revision ID: fc125248c2cd
Revises: 7968a2aac1a5
Create Date: 2025-06-02 16:23:04.513340

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc125248c2cd"
down_revision: Union[str, None] = "7968a2aac1a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("responses", sa.Column("displayed_page", sa.Integer(), nullable=True))
    op.add_column(
        "responses", sa.Column("displayed_ordering", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("responses", "displayed_ordering")
    op.drop_column("responses", "displayed_page")
    # ### end Alembic commands ###
